import type {Metadata} from "next";
import localFont from "next/font/local";
import "./styles/index.scss";
import {ReactNode} from "react";
import Image from "next/image";
import {Navbar} from "widgets/Navbar";
import {Footer} from "widgets/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sadik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} app theme-light`}>
        <section className='header'>
          <div className='layout-title'>
            <Image src='/assets/images/placeholder.jpg' alt={''} height={300} width={1000} style={{width:'100%', objectFit:'cover'}} />
            <h1>Детский сад</h1>
          </div>
          <Navbar />
        </section>
        <section className='main'>
          <div className='wrapper'>
          {children}
          </div>
        </section>
        <Footer />
      </body>
    </html>
  );
}
